# Generated by Django 5.0.1 on 2024-01-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subject',
            field=models.CharField(default='new chat', max_length=256),
        ),
    ]
